cc_library(
    name = "conditions",
    srcs = [
    ],
    hdrs = [
        "bleeding.h",
        "deep_wound.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//character",
    ],
)

cc_test(
    name = "test",
    size = "small",
    srcs = [
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)
